1. 목록 조회 -> 2. ID 추출 -> 3. 상세 조회

# API로 데이터 가져오기 테스트

In [68]:
import json
import requests

key = "3ee851822ac974d2b7d447a4d6da1eac83d489b1a0e0e647c56af6aa602f60e5"
url = "https://apis.data.go.kr/B551011/KorService2/areaBasedList2"


# 요청 파라미터
params = {
    'serviceKey': key,
    'numOfRows': '10',
    'pageNo': '1',
    'MobileOS': 'ETC',
    'MobileApp': 'AppTest',
    '_type': 'json',
    'contentId':'126128'
    }

r = requests.get(url, params=params)
data = r.json()
print(data)

{'responseTime': '2026-04-17T01:32:21.425', 'resultCode': '10', 'resultMsg': 'INVALID_REQUEST_PARAMETER_ERROR(contentId)'}

In [69]:
data

{'responseTime': '2026-04-17T01:32:21.425',
 'resultCode': '10',
 'resultMsg': 'INVALID_REQUEST_PARAMETER_ERROR(contentId)'}

In [ ]:
# 원하는 정보만 필터링
import requests
import json

def get_tourism_data(lDongRegnCd, content_type, lDongSignguCd=None):
    key = "3ee851822ac974d2b7d447a4d6da1eac83d489b1a0e0e647c56af6aa602f60e5"
    url = "https://apis.data.go.kr/B551011/KorService2/areaBasedList2"

    params = {
        'serviceKey': key,
        'numOfRows': '10',
        'pageNo': '1',
        'MobileOS': 'ETC',
        'MobileApp': 'Tripto',
        '_type': 'json',
        'arrange': 'A',                # A=제목순 
        'lDongRegnCd' : lDongRegnCd,   # 법정동 시도 코드
        'contentTypeId': content_type  # 12: 관광지, 32: 숙박, 39: 음식점 
    }

    # 있으면 파라미터 추가
    if lDongSignguCd:
        params['lDongSignguCd'] = lDongSignguCd

    response = requests.get(url, params=params)
    return response.json()



code_list = [
    {"name":"서울", "code":"11"},
    {"name":"부산", "code":"26"},
    {"name":"김포", "code":"41","code_2":"570"},
]


def find_code(city_name):
    # 도시명으로 검색하여 (시도코드, 시군구코드) 튜플 반환
    for item in code_list:
        if item['name'] == city_name:
            return item.get('code'), item.get('code_2')
    return None, None

city_name = input("어느 지역을 원하시나요?")
code, code_2 = find_code(city_name)

# 1. 관광지(12) 정보 가져오기
tourist_spots = get_tourism_data(code, '12', code_2)
print("--- 관광지 목록 ---")
print(tourist_spots)

# 2. 음식점(39) 정보 가져오기
restaurants = get_tourism_data(code, '39', code_2)
print("\n--- 음식점 목록 ---")
print(restaurants)

# 3. 숙박(32) 가져오기
Accommodation = get_tourism_data(code, '32', code_2)
print("\n--- 숙박 목록 ---")
print(Accommodation)

--- 관광지 목록 ---
{'response': {'header': {'resultCode': '0000', 'resultMsg': 'OK'}, 'body': {'items': {'item': [{'addr1': '경기도 김포시 걸포로 80-46 (걸포동)', 'addr2': '', 'areacode': '31', 'cat1': 'A02', 'cat2': 'A0202', 'cat3': 'A02020700', 'contentid': '753801', 'contenttypeid': '12', 'createdtime': '20090617012330', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/72/3077072_image2_1.jpg', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/72/3077072_image3_1.jpg', 'cpyrhtDivCd': 'Type3', 'mapx': '126.7064132635', 'mapy': '37.6386715536', 'mlevel': '6', 'modifiedtime': '20250430164548', 'sigungucode': '8', 'tel': '', 'title': '걸포중앙공원', 'zipcode': '10099', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'VE', 'lclsSystm2': 'VE03', 'lclsSystm3': 'VE030100'}, {'addr1': '경기도 김포시 하성면 마곡로72번길 275', 'addr2': '', 'areacode': '', 'cat1': '', 'cat2': '', 'cat3': '', 'contentid': '4032721', 'contenttypeid': '12', 'createdtime': '20260305151700', 'firstimage': 'https://tong.visitkorea.or.kr/cms/resource/43/4032643_image2_1.jpg', 'firstimage2': 'https://tong.visitkorea.or.kr/cms/resource/43/4032643_image3_1.jpg', 'cpyrhtDivCd': 'Type3', 'mapx': '126.660030711278', 'mapy': '37.7108902755135', 'mlevel': '', 'modifiedtime': '20260309093631', 'sigungucode': '', 'tel': '', 'title': '금나루전통장체험농장', 'zipcode': '10012', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'EX', 'lclsSystm2': 'EX03', 'lclsSystm3': 'EX030300'}, {'addr1': '경기도 김포시 승가로 125 (풍무동)', 'addr2': '', 'areacode': '31', 'cat1': 'A02', 'cat2': 'A0201', 'cat3': 'A02010800', 'contentid': '298113', 'contenttypeid': '12', 'createdtime': '20071127233517', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/38/3547038_image2_1.jpg', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/38/3547038_image3_1.jpg', 'cpyrhtDivCd': 'Type3', 'mapx': '126.7090000202', 'mapy': '37.6072391473', 'mlevel': '6', 'modifiedtime': '20251023143000', 'sigungucode': '8', 'tel': '', 'title': '금정사(김포)', 'zipcode': '10118', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'HS', 'lclsSystm2': 'HS03', 'lclsSystm3': 'HS030100'}, {'addr1': '경기도 김포시 대명항1로 109', 'addr2': '', 'areacode': '31', 'cat1': 'A01', 'cat2': 'A0101', 'cat3': 'A01011400', 'contentid': '228863', 'contenttypeid': '12', 'createdtime': '20031209090000', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/34/3501734_image2_1.jpg', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/34/3501734_image3_1.jpg', 'cpyrhtDivCd': 'Type1', 'mapx': '126.5417171922', 'mapy': '37.6394407719', 'mlevel': '6', 'modifiedtime': '20250701164333', 'sigungucode': '8', 'tel': '', 'title': '김포 대명항', 'zipcode': '10041', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'NA', 'lclsSystm2': 'NA02', 'lclsSystm3': 'NA020700'}, {'addr1': '경기도 김포시 대곶면 덕포진로103번길 130', 'addr2': '', 'areacode': '31', 'cat1': 'A02', 'cat2': 'A0201', 'cat3': 'A02010200', 'contentid': '127402', 'contenttypeid': '12', 'createdtime': '20030630090000', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/62/3506462_image2_1.jpg', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/62/3506462_image3_1.jpg', 'cpyrhtDivCd': 'Type1', 'mapx': '126.5366756976', 'mapy': '37.6498366936', 'mlevel': '6', 'modifiedtime': '20250731085512', 'sigungucode': '8', 'tel': '', 'title': '김포 덕포진', 'zipcode': '10041', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'HS', 'lclsSystm2': 'HS01', 'lclsSystm3': 'HS010200'}, {'addr1': '경기도 김포시 월곶면 성동리', 'addr2': '산36-1', 'areacode': '', 'cat1': '', 'cat2': '', 'cat3': '', 'contentid': '125544', 'contenttypeid': '12', 'createdtime': '20021202090000', 'firstimage': 'https://tong.visitkorea.or.kr/cms/resource/76/3507176_image2_1.jpg', 'firstimage2': 'https://tong.visitkorea.or.kr/cms/resource/76/3507176_image3_1.jpg', 'cpyrhtDivCd': 'Type1', 'mapx': '126.5309', 'mapy': '37.7421', 'mlevel': '6', 'modifiedtime': '20260311100340', 'sigungucode': '', 'tel': '', 'title': '김포 문수산성', 'zipcode': '10000', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'HS', 'lclsSystm2': 'HS01', 'lclsSystm3': 'HS010200'}, {'addr1': '경기도 김포시 김포한강11로 455', 'addr2': '', 'areacode': '31', 'cat1': 'A01', 'cat2': 'A0101', 'cat3': 'A01010500', 'contentid': '2653113', 'contenttypeid': '12', 'createdtime': '20200420221842', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/91/3404791_image2_1.JPG', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/91/3404791_image3_1.JPG', 'cpyrhtDivCd': 'Type3', 'mapx': '126.6993634541', 'mapy': '37.6548362130', 'mlevel': '6', 'modifiedtime': '20250325170110', 'sigungucode': '8', 'tel': '', 'title': '김포 사색의 길', 'zipcode': '10074', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'NA', 'lclsSystm2': 'NA05', 'lclsSystm3': 'NA050100'}, {'addr1': '경기도 김포시 대곶면 율생리', 'addr2': '산117', 'areacode': '31', 'cat1': 'A02', 'cat2': 'A0201', 'cat3': 'A02010200', 'contentid': '127403', 'contenttypeid': '12', 'createdtime': '20021202090000', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/32/3527732_image2_1.jpg', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/32/3527732_image3_1.jpg', 'cpyrhtDivCd': 'Type1', 'mapx': '126.5889434511', 'mapy': '37.6386055916', 'mlevel': '6', 'modifiedtime': '20250904150957', 'sigungucode': '8', 'tel': '', 'title': '김포 수안산성', 'zipcode': '10039', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'HS', 'lclsSystm2': 'HS01', 'lclsSystm3': 'HS010200'}, {'addr1': '경기도 김포시 장릉로 79 (풍무동)', 'addr2': '', 'areacode': '31', 'cat1': 'A02', 'cat2': 'A0201', 'cat3': 'A02010700', 'contentid': '126542', 'contenttypeid': '12', 'createdtime': '20021202090000', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/50/3361650_image2_1.jpg', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/50/3361650_image3_1.jpg', 'cpyrhtDivCd': 'Type3', 'mapx': '126.7155881596', 'mapy': '37.6125164284', 'mlevel': '6', 'modifiedtime': '20250320135027', 'sigungucode': '8', 'tel': '', 'title': '김포 장릉(원종·인헌왕후) [유네스코 세계유산]', 'zipcode': '10118', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'HS', 'lclsSystm2': 'HS01', 'lclsSystm3': 'HS010800'}, {'addr1': '경기도 김포시 고촌읍 황어로350번길 48', 'addr2': '', 'areacode': '31', 'cat1': 'A02', 'cat2': 'A0203', 'cat3': 'A02030100', 'contentid': '3081486', 'contenttypeid': '12', 'createdtime': '20230919121231', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/77/3081477_image2_1.JPG', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/77/3081477_image3_1.JPG', 'cpyrhtDivCd': 'Type3', 'mapx': '126.7555768413', 'mapy': '37.5887310174', 'mlevel': '6', 'modifiedtime': '20250430175917', 'sigungucode': '8', 'tel': '', 'title': '김포곤충농장', 'zipcode': '10132', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'EX', 'lclsSystm2': 'EX03', 'lclsSystm3': 'EX030300'}]}, 'numOfRows': 10, 'pageNo': 1, 'totalCount': 47}}}

--- 음식점 목록 ---
{'response': {'header': {'resultCode': '0000', 'resultMsg': 'OK'}, 'body': {'items': {'item': [{'addr1': '경기도 김포시 양촌읍 김포한강4로 317', 'addr2': '', 'areacode': '', 'cat1': '', 'cat2': '', 'cat3': '', 'contentid': '2863282', 'contenttypeid': '39', 'createdtime': '20221004152953', 'firstimage': 'https://tong.visitkorea.or.kr/cms/resource/66/2863266_image2_1.jpg', 'firstimage2': 'https://tong.visitkorea.or.kr/cms/resource/66/2863266_image3_1.jpg', 'cpyrhtDivCd': 'Type3', 'mapx': '126.64803153019128', 'mapy': '37.65079583509287', 'mlevel': '6', 'modifiedtime': '20260305102058', 'sigungucode': '', 'tel': '', 'title': '갈비본질 프리미엄', 'zipcode': '10065', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'FD', 'lclsSystm2': 'FD01', 'lclsSystm3': 'FD010100'}, {'addr1': '경기도 김포시 고촌읍 전호로 68', 'addr2': '', 'areacode': '31', 'cat1': 'A05', 'cat2': 'A0502', 'cat3': 'A05020100', 'contentid': '2860557', 'contenttypeid': '39', 'createdtime': '20220927105341', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/47/2860547_image2_1.jpg', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/47/2860547_image3_1.jpg', 'cpyrhtDivCd': 'Type3', 'mapx': '126.7923702784', 'mapy': '37.6038715774', 'mlevel': '6', 'modifiedtime': '20250502165411', 'sigungucode': '8', 'tel': '', 'title': '강원막국수', 'zipcode': '10135', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'FD', 'lclsSystm2': 'FD01', 'lclsSystm3': 'FD010100'}, {'addr1': '경기도 김포시 양촌읍 김포대로1750번길 29', 'addr2': '', 'areacode': '31', 'cat1': 'A05', 'cat2': 'A0502', 'cat3': 'A05020900', 'contentid': '2742141', 'contenttypeid': '39', 'createdtime': '20210909194514', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/55/2742655_image2_1.jpg', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/55/2742655_image3_1.jpg', 'cpyrhtDivCd': 'Type3', 'mapx': '126.6448318825', 'mapy': '37.6707528360', 'mlevel': '6', 'modifiedtime': '20250430175743', 'sigungucode': '8', 'tel': '', 'title': '견생역전', 'zipcode': '10052', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'FD', 'lclsSystm2': 'FD05', 'lclsSystm3': 'FD050100'}, {'addr1': '경기도 김포시 김포한강9로75번길 22 (구래동)', 'addr2': '', 'areacode': '31', 'cat1': 'A05', 'cat2': 'A0502', 'cat3': 'A05020200', 'contentid': '2844395', 'contenttypeid': '39', 'createdtime': '20220826103121', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/91/2844391_image2_1.jpg', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/91/2844391_image3_1.jpg', 'cpyrhtDivCd': 'Type3', 'mapx': '126.6240345374', 'mapy': '37.6439222594', 'mlevel': '6', 'modifiedtime': '20250502112327', 'sigungucode': '8', 'tel': '', 'title': '겸손돈가스', 'zipcode': '10071', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'FD', 'lclsSystm2': 'FD02', 'lclsSystm3': 'FD020300'}, {'addr1': '경기도 김포시 김포한강1로84번길 14 (장기동)', 'addr2': '', 'areacode': '31', 'cat1': 'A05', 'cat2': 'A0502', 'cat3': 'A05020300', 'contentid': '2844415', 'contenttypeid': '39', 'createdtime': '20220826113301', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/11/2844411_image2_1.jpg', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/11/2844411_image3_1.jpg', 'cpyrhtDivCd': 'Type3', 'mapx': '126.6711301931', 'mapy': '37.6452618266', 'mlevel': '6', 'modifiedtime': '20250502112324', 'sigungucode': '8', 'tel': '', 'title': '교다이', 'zipcode': '10079', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'FD', 'lclsSystm2': 'FD02', 'lclsSystm3': 'FD020200'}, {'addr1': '경기도 김포시 대곶면 대명항로 369', 'addr2': '', 'areacode': '31', 'cat1': 'A05', 'cat2': 'A0502', 'cat3': 'A05020100', 'contentid': '2853048', 'contenttypeid': '39', 'createdtime': '20220914110148', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/34/2853034_image2_1.jpg', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/34/2853034_image3_1.jpg', 'cpyrhtDivCd': 'Type3', 'mapx': '126.5800578802', 'mapy': '37.6483487447', 'mlevel': '6', 'modifiedtime': '20250502150127', 'sigungucode': '8', 'tel': '', 'title': '국보966옛날두부', 'zipcode': '10043', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'FD', 'lclsSystm2': 'FD01', 'lclsSystm3': 'FD010100'}, {'addr1': '경기도 김포시 돌문로62번길 5-16', 'addr2': '', 'areacode': '31', 'cat1': 'A05', 'cat2': 'A0502', 'cat3': 'A05020100', 'contentid': '134829', 'contenttypeid': '39', 'createdtime': '20050111090000', 'firstimage': '', 'firstimage2': '', 'cpyrhtDivCd': '', 'mapx': '126.7159823376', 'mapy': '37.6207265905', 'mlevel': '6', 'modifiedtime': '20250320160811', 'sigungucode': '8', 'tel': '031-997-6866', 'title': '군산아구꽃게해물찜탕', 'zipcode': '10108', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'FD', 'lclsSystm2': 'FD01', 'lclsSystm3': 'FD010100'}, {'addr1': '경기도 김포시 양촌읍 구래로87번길 137', 'addr2': '', 'areacode': '31', 'cat1': 'A05', 'cat2': 'A0502', 'cat3': 'A05020100', 'contentid': '2844423', 'contenttypeid': '39', 'createdtime': '20220826113936', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/19/2844419_image2_1.jpg', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/19/2844419_image3_1.jpg', 'cpyrhtDivCd': 'Type3', 'mapx': '126.6131382447', 'mapy': '37.6463217870', 'mlevel': '6', 'modifiedtime': '20250502112337', 'sigungucode': '8', 'tel': '', 'title': '그집', 'zipcode': '10058', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'FD', 'lclsSystm2': 'FD01', 'lclsSystm3': 'FD010100'}, {'addr1': '경기도 김포시 김포대로319번길 47', 'addr2': '', 'areacode': '31', 'cat1': 'A05', 'cat2': 'A0502', 'cat3': 'A05020100', 'contentid': '2860581', 'contenttypeid': '39', 'createdtime': '20220927105854', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/71/2860571_image2_1.jpg', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/71/2860571_image3_1.jpg', 'cpyrhtDivCd': 'Type3', 'mapx': '126.7714945871', 'mapy': '37.5974775051', 'mlevel': '6', 'modifiedtime': '20250115152603', 'sigungucode': '8', 'tel': '', 'title': '김구원선생두부', 'zipcode': '10129', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'FD', 'lclsSystm2': 'FD01', 'lclsSystm3': 'FD010100'}, {'addr1': '경기도 김포시 양촌읍 김포한강10로 91', 'addr2': '', 'areacode': '31', 'cat1': 'A05', 'cat2': 'A0502', 'cat3': 'A05020100', 'contentid': '2844429', 'contenttypeid': '39', 'createdtime': '20220826114445', 'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/24/2844424_image2_1.jpg', 'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/24/2844424_image3_1.jpg', 'cpyrhtDivCd': 'Type3', 'mapx': '126.6224710216', 'mapy': '37.6356870803', 'mlevel': '6', 'modifiedtime': '20250502112816', 'sigungucode': '8', 'tel': '', 'title': '김반장오리주물럭 앤펍', 'zipcode': '10045', 'lDongRegnCd': '41', 'lDongSignguCd': '570', 'lclsSystm1': 'FD', 'lclsSystm2': 'FD01', 'lclsSystm3': 'FD010100'}]}, 'numOfRows': 10, 'pageNo': 1, 'totalCount': 100}}}

--- 숙박 목록 ---

다만 숙소에 가격 정보가 없음

->  여기서 검색 후 자동화로 타 사이트에서 검색 가능?

-> 여기서 대략적 금액 가능?

In [71]:
Accommodation

{'response': {'header': {'resultCode': '0000', 'resultMsg': 'OK'},
  'body': {'items': {'item': [{'addr1': '경기도 김포시 모담공원로 170 (운양동)',
      'addr2': '',
      'areacode': '31',
      'cat1': 'B02',
      'cat2': 'B0201',
      'cat3': 'B02011600',
      'contentid': '2574186',
      'contenttypeid': '32',
      'createdtime': '20181206014439',
      'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/35/3535435_image2_1.jpg',
      'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/35/3535435_image3_1.jpg',
      'cpyrhtDivCd': 'Type3',
      'mapx': '126.6962278583',
      'mapy': '37.6466871063',
      'mlevel': '6',
      'modifiedtime': '20250915150110',
      'sigungucode': '8',
      'tel': '',
      'title': '김포아트빌리지 전통한옥숙박체험관',
      'zipcode': '10077',
      'lDongRegnCd': '41',
      'lDongSignguCd': '570',
      'lclsSystm1': 'AC',
      'lclsSystm2': 'AC03',
      'lclsSystm3': 'AC030200'},
     {'addr1': '경기도 김포시 고촌읍 아라육로152번길 169',
      'addr2': '',
      'areacode': '31',
      'cat1': 'B02',
      'cat2': 'B0201',
      'cat3': 'B02010100',
      'contentid': '2874683',
      'contenttypeid': '32',
      'createdtime': '20221025135611',
      'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/76/2874676_image2_1.jpg',
      'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/76/2874676_image3_1.jpg',
      'cpyrhtDivCd': 'Type3',
      'mapx': '126.7859014954',
      'mapy': '37.6013634210',
      'mlevel': '6',
      'modifiedtime': '20250730105522',
      'sigungucode': '8',
      'tel': '',
      'title': '라마다앙코르 바이윈덤 김포한강호텔',
      'zipcode': '10135',
      'lDongRegnCd': '41',
      'lDongSignguCd': '570',
      'lclsSystm1': 'AC',
      'lclsSystm2': 'AC01',
      'lclsSystm3': 'AC010100'},
     {'addr1': '경기도 김포시 태장로795번길 151',
      'addr2': '',
      'areacode': '31',
      'cat1': 'B02',
      'cat2': 'B0201',
      'cat3': 'B02010100',
      'contentid': '2894945',
      'contenttypeid': '32',
      'createdtime': '20221103153423',
      'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/31/2894931_image2_1.JPG',
      'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/31/2894931_image2_1.JPG',
      'cpyrhtDivCd': 'Type3',
      'mapx': '126.6851123961',
      'mapy': '37.6399821341',
      'mlevel': '6',
      'modifiedtime': '20250508154744',
      'sigungucode': '8',
      'tel': '',
      'title': '레스트호텔',
      'zipcode': '10090',
      'lDongRegnCd': '41',
      'lDongSignguCd': '570',
      'lclsSystm1': 'AC',
      'lclsSystm2': 'AC01',
      'lclsSystm3': 'AC010100'},
     {'addr1': '경기도 김포시 대곶면 약암로 879',
      'addr2': '',
      'areacode': '31',
      'cat1': 'B02',
      'cat2': 'B0201',
      'cat3': 'B02010100',
      'contentid': '2918735',
      'contenttypeid': '32',
      'createdtime': '20221027144304',
      'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/91/2877391_image2_1.jpg',
      'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/91/2877391_image3_1.jpg',
      'cpyrhtDivCd': 'Type3',
      'mapx': '126.5534690907',
      'mapy': '37.6324251296',
      'mlevel': '6',
      'modifiedtime': '20250626161931',
      'sigungucode': '8',
      'tel': '',
      'title': '루브호텔',
      'zipcode': '10042',
      'lDongRegnCd': '41',
      'lDongSignguCd': '570',
      'lclsSystm1': 'AC',
      'lclsSystm2': 'AC01',
      'lclsSystm3': 'AC010100'},
     {'addr1': '경기도 김포시 태장로795번길 147 (장기동)',
      'addr2': '',
      'areacode': '31',
      'cat1': 'B02',
      'cat2': 'B0201',
      'cat3': 'B02010100',
      'contentid': '2870003',
      'contenttypeid': '32',
      'createdtime': '20221019101611',
      'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/37/2869937_image2_1.jpg',
      'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/37/2869937_image3_1.jpg',
      'cpyrhtDivCd': 'Type3',
      'mapx': '126.6846707604',
      'mapy': '37.6403237533',
      'mlevel': '6',
      'modifiedtime': '20250502175549',
      'sigungucode': '8',
      'tel': '',
      'title': '스타비아호텔',
      'zipcode': '10090',
      'lDongRegnCd': '41',
      'lDongSignguCd': '570',
      'lclsSystm1': 'AC',
      'lclsSystm2': 'AC01',
      'lclsSystm3': 'AC010100'},
     {'addr1': '경기도 김포시 태장로795번길 123 (장기동)',
      'addr2': '',
      'areacode': '31',
      'cat1': 'B02',
      'cat2': 'B0201',
      'cat3': 'B02010100',
      'contentid': '2870042',
      'contenttypeid': '32',
      'createdtime': '20221019102340',
      'firstimage': '',
      'firstimage2': '',
      'cpyrhtDivCd': '',
      'mapx': '126.6839069774',
      'mapy': '37.6390377783',
      'mlevel': '6',
      'modifiedtime': '20250508142859',
      'sigungucode': '8',
      'tel': '',
      'title': '아리수호텔',
      'zipcode': '10090',
      'lDongRegnCd': '41',
      'lDongSignguCd': '570',
      'lclsSystm1': 'AC',
      'lclsSystm2': 'AC01',
      'lclsSystm3': 'AC010100'},
     {'addr1': '경기도 김포시 김포한강9로75번길 72 (구래동)',
      'addr2': '',
      'areacode': '31',
      'cat1': 'B02',
      'cat2': 'B0201',
      'cat3': 'B02010100',
      'contentid': '2874896',
      'contenttypeid': '32',
      'createdtime': '20221025144952',
      'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/83/2874883_image2_1.jpg',
      'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/83/2874883_image2_1.jpg',
      'cpyrhtDivCd': 'Type3',
      'mapx': '126.6216514362',
      'mapy': '37.6433945010',
      'mlevel': '6',
      'modifiedtime': '20250508150502',
      'sigungucode': '8',
      'tel': '',
      'title': '저스트슬립호텔 김포구래1호점',
      'zipcode': '10071',
      'lDongRegnCd': '41',
      'lDongSignguCd': '570',
      'lclsSystm1': 'AC',
      'lclsSystm2': 'AC01',
      'lclsSystm3': 'AC010100'},
     {'addr1': '경기도 김포시 월곶면 용강로250번길 104',
      'addr2': '',
      'areacode': '31',
      'cat1': 'B02',
      'cat2': 'B0201',
      'cat3': 'B02011300',
      'contentid': '3316414',
      'contenttypeid': '32',
      'createdtime': '20240619100753',
      'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/07/3316407_image2_1.jpg',
      'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/07/3316407_image3_1.jpg',
      'cpyrhtDivCd': 'Type3',
      'mapx': '126.5655065940',
      'mapy': '37.7418764745',
      'mlevel': '6',
      'modifiedtime': '20250320105249',
      'sigungucode': '8',
      'tel': '031-8049-3960',
      'title': '조강276(DMZ 평화의 길 거점센터)',
      'zipcode': '10002',
      'lDongRegnCd': '41',
      'lDongSignguCd': '570',
      'lclsSystm1': 'AC',
      'lclsSystm2': 'AC02',
      'lclsSystm3': 'AC020200'},
     {'addr1': '경기도 김포시 태장로795번길 111 (장기동)',
      'addr2': '',
      'areacode': '31',
      'cat1': 'B02',
      'cat2': 'B0201',
      'cat3': 'B02010100',
      'contentid': '2870106',
      'contenttypeid': '32',
      'createdtime': '20221019104745',
      'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/82/2870082_image2_1.jpg',
      'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/82/2870082_image3_1.jpg',
      'cpyrhtDivCd': 'Type3',
      'mapx': '126.6835681289',
      'mapy': '37.6387017003',
      'mlevel': '6',
      'modifiedtime': '20250626154247',
      'sigungucode': '8',
      'tel': '',
      'title': '펜타스타호텔',
      'zipcode': '10090',
      'lDongRegnCd': '41',
      'lDongSignguCd': '570',
      'lclsSystm1': 'AC',
      'lclsSystm2': 'AC01',
      'lclsSystm3': 'AC010100'},
     {'addr1': '경기도 김포시 고촌읍 장차로5번길 5-9',
      'addr2': '',
      'areacode': '31',
      'cat1': 'B02',
      'cat2': 'B0201',
      'cat3': 'B02010100',
      'contentid': '2874916',
      'contenttypeid': '32',
      'createdtime': '20221025145938',
      'firstimage': 'http://tong.visitkorea.or.kr/cms/resource/04/2874904_image2_1.jpg',
      'firstimage2': 'http://tong.visitkorea.or.kr/cms/resource/04/2874904_image2_1.jpg',
      'cpyrhtDivCd': 'Type3',
      'mapx': '126.7693113040',
      'mapy': '37.6027740722',
      'mlevel': '6',
      'modifiedtime': '20250508150859',
      'sigungucode': '8',
      'tel': '',
      'title': '호텔 라르 김포',
      'zipcode': '10126',
      'lDongRegnCd': '41',
      'lDongSignguCd': '570',
      'lclsSystm1': 'AC',
      'lclsSystm2': 'AC01',
      'lclsSystm3': 'AC010100'}]},
   'numOfRows': 10,
   'pageNo': 1,
   'totalCount': 13}}}

In [73]:
Accommodations = []

# 데이터 리스트를 가져옵니다. [cite: 156, 178]
target_list = Accommodation['response']['body']['items']['item']

for i in target_list:
    # i는 이제 각 숙박시설의 정보가 담긴 '딕셔너리'입니다.
    Accommodations.append(i)

df = pd.DataFrame(Accommodations)

In [87]:
df.head()

,addr1,addr2,areacode,cat1,cat2,cat3,contentid,contenttypeid,createdtime,firstimage,...,modifiedtime,sigungucode,tel,title,zipcode,lDongRegnCd,lDongSignguCd,lclsSystm1,lclsSystm2,lclsSystm3
0,경기도 김포시 모담공원로 170 (운양동),,31,B02,B0201,B02011600,2574186,32,20181206014439,http://tong.visitkorea.or.kr/cms/resource/35/3...,...,20250915150110,8,,김포아트빌리지 전통한옥숙박체험관,10077,41,570,AC,AC03,AC030200
1,경기도 김포시 고촌읍 아라육로152번길 169,,31,B02,B0201,B02010100,2874683,32,20221025135611,http://tong.visitkorea.or.kr/cms/resource/76/2...,...,20250730105522,8,,라마다앙코르 바이윈덤 김포한강호텔,10135,41,570,AC,AC01,AC010100
2,경기도 김포시 태장로795번길 151,,31,B02,B0201,B02010100,2894945,32,20221103153423,http://tong.visitkorea.or.kr/cms/resource/31/2...,...,20250508154744,8,,레스트호텔,10090,41,570,AC,AC01,AC010100
3,경기도 김포시 대곶면 약암로 879,,31,B02,B0201,B02010100,2918735,32,20221027144304,http://tong.visitkorea.or.kr/cms/resource/91/2...,...,20250626161931,8,,루브호텔,10042,41,570,AC,AC01,AC010100
4,경기도 김포시 태장로795번길 147 (장기동),,31,B02,B0201,B02010100,2870003,32,20221019101611,http://tong.visitkorea.or.kr/cms/resource/37/2...,...,20250502175549,8,,스타비아호텔,10090,41,570,AC,AC01,AC010100

In [82]:
df.columns

Index(['addr1', 'addr2', 'areacode', 'cat1', 'cat2', 'cat3', 'contentid',
       'contenttypeid', 'createdtime', 'firstimage', 'firstimage2',
       'cpyrhtDivCd', 'mapx', 'mapy', 'mlevel', 'modifiedtime', 'sigungucode',
       'tel', 'title', 'zipcode', 'lDongRegnCd', 'lDongSignguCd', 'lclsSystm1',
       'lclsSystm2', 'lclsSystm3'],
      dtype='object')

In [88]:
df[["title","contentid", "contenttypeid"]]

                   title contentid contenttypeid
0      김포아트빌리지 전통한옥숙박체험관   2574186            32
1     라마다앙코르 바이윈덤 김포한강호텔   2874683            32
2                  레스트호텔   2894945            32
3                   루브호텔   2918735            32
4                 스타비아호텔   2870003            32
5                  아리수호텔   2870042            32
6        저스트슬립호텔 김포구래1호점   2874896            32
7  조강276(DMZ 평화의 길 거점센터)   3316414            32
8                 펜타스타호텔   2870106            32
9               호텔 라르 김포   2874916            32

In [91]:
id = df["contentid"]
type = df["contenttypeid"]

In [103]:
df.shape

(10, 25)

In [96]:
# 반복 정보 조회

def search (id, type):
    key = "3ee851822ac974d2b7d447a4d6da1eac83d489b1a0e0e647c56af6aa602f60e5"
    url = "http://apis.data.go.kr/B551011/KorService2/detailInfo2"

    # 요청 파라미터
    params = {
        'serviceKey': key,
        'numOfRows': '10',
        'pageNo': '1',
        'MobileOS': 'ETC',
        'MobileApp': 'Tripto',
        '_type': 'json',
        'contentId' : id,   
        'contentTypeId': type  # 12: 관광지, 32: 숙박, 39: 음식점
    }
    
    response = requests.get(url, params=params)
    return response.json()


all_details = []

for id, type in zip(df["contentid"], df["contenttypeid"]):
    print("조회중")
    reault = search (id, type)

    # 데이터가 정상적으로 왔는지 확인 후 리스트에 추가
    if reault and 'response' in reault and 'body' in reault['response']:
        items = reault['response']['body']['items']
        if items: # 데이터가 있는 경우만
            # 반복 정보는 한 ID당 여러 개(item 리스트)일 수 있으므로 extend 사용
            all_details.extend(items['item'])

조회중
조회중
조회중
조회중
조회중
조회중
조회중
조회중
조회중
조회중

In [99]:
# 3. 전체 결과를 다시 데이터프레임으로 변환
df_details = pd.DataFrame(all_details)
df_details

,contentid,contenttypeid,roomcode,roomtitle,roomsize1,roomcount,roombasecount,roommaxcount,roomoffseasonminfee1,roomoffseasonminfee2,...,cpyrhtDivCd2,roomimg3,roomimg3alt,cpyrhtDivCd3,roomimg4,roomimg4alt,cpyrhtDivCd4,roomimg5,roomimg5alt,cpyrhtDivCd5
0,2874683,32,,슈페리어 더블,6,150,2,3,90000,100000,...,,,,,,,,,,
1,2874683,32,,슈페리어 트윈,6,242,2,2,90000,100000,...,,,,,,,,,,
2,2874683,32,,주니어 스위트 더블,13,11,2,2,180000,220000,...,,,,,,,,,,
3,2874683,32,,디럭스패밀리 트윈,6,166,2,3,100000,110000,...,,,,,,,,,,
4,2894945,32,,executive/ Sunbed Twin,13,20,2,3,250000,300000,...,,,,,,,,,,
5,2894945,32,,Premier/ Deluxe Double,13,35,2,3,230000,250000,...,,,,,,,,,,
6,2894945,32,,Junior/Coner Suite,13,15,2,3,230000,250000,...,,,,,,,,,,
7,2918735,32,,VIP,12,3,2,3,120000,150000,...,,,,,,,,,,
8,2918735,32,,Primium,10,3,2,3,60000,80000,...,,,,,,,,,,
9,2918735,32,,Deluxe,5,6,2,3,50000,60000,...,,,,,,,,,,
10,2918735,32,,Standard,5,26,2,3,40000,50000,...,,,,,,,,,,
11,2870003,32,,Deluxe/ Premiere Double,13,40,2,3,80000,95000,...,,,,,,,,,,
12,2870003,32,,Terrace Suite,13,9,2,3,110000,140000,...,,,,,,,,,,
13,2870003,32,,Spa Garden Terrace Triple,13,8,2,3,300000,400000,...,,,,,,,,,,
14,2870003,32,,Terrace Premiere/ Suite Double,13,12,2,3,100000,120000,...,,,,,,,,,,
15,2870042,32,,Deluxe,13,2,2,3,120000,130000,...,,,,,,,,,,
16,2870042,32,,Semi-Deluxe,13,10,2,3,100000,110000,...,,,,,,,,,,
17,2870042,32,,Suite,0,2,2,3,180000,220000,...,,,,,,,,,,
18,2870042,32,,Standard/ Royal Standard,13,42,2,3,90000,100000,...,,,,,,,,,,
19,2874896,32,,Primium Twin,4,3,3,3,70000,130000,...,,,,,,,,,,
20,2874896,32,,VIP,4,3,2,3,75000,140000,...,,,,,,,,,,
21,2874896,32,,Deluxe,4,5,2,3,60000,120000,...,,,,,,,,,,
22,2874896,32,,Standard,3,21,2,3,50000,100000,...,,,,,,,,,,
23,3316414,32,,다방,0,1,1,1,0,0,...,Type3,http://tong.visitkorea.or.kr/cms/resource/00/3...,조강276_다방 (3),Type3,,,,,,
24,3316414,32,,가방,0,1,1,4,0,0,...,Type3,http://tong.visitkorea.or.kr/cms/resource/94/3...,조강276_가방 (3),Type3,,,,,,
25,3316414,32,,라방,0,1,1,1,0,0,...,Type3,http://tong.visitkorea.or.kr/cms/resource/03/3...,조강276_라방 (3),Type3,,,,,,
26,3316414,32,,나방,0,1,1,4,0,0,...,Type3,http://tong.visitkorea.or.kr/cms/resource/97/3...,조강276_나방 (3),Type3,,,,,,
27,2870106,32,,Semi-Suite/ Family Room,13,3,2,3,100000,120000,...,,,,,,,,,,
28,2870106,32,,Standard Twin/ Game Room,13,8,2,3,70000,80000,...,,,,,,,,,,
29,2870106,32,,Standard/ Deluxe Double,13,40,2,3,65000,75000,...,,,,,,,,,,
30,2870106,32,,Deluxe Twin/ Sky Double,13,11,2,3,80000,100000,...,,,,,,,,,,
31,2874916,32,,King Double,3,24,2,2,700000,80000,...,,,,,,,,,,
32,2874916,32,,Royal Suite,3,1,3,3,500000,500000,...,,,,,,,,,,
33,2874916,32,,Junior Suite,6,4,2,3,90000,100000,...,,,,,,,,,,
34,2874916,32,,Deluxe Twin,3,115,2,3,80000,90000,...,,,,,,,,,,